/*
 * File: app/view/grid/Basic.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.grid.Basic', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.samplebasicgrid',

    requires: [
        'euisa.view.grid.BasicViewModel',
        'euisa.view.grid.BasicViewController',
        'eui.grid.Panel',
        'Ext.view.Table',
        'eui.toolbar.Command',
        'Ext.grid.plugin.CellEditing',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text'
    ],

    controller: 'samplebasicgrid',
    viewModel: {
        type: 'samplebasicgrid'
    },
    layout: 'fit',
    title: '#{행추가2}',

    items: [
        {
            xtype: 'euigrid',
            usePagingToolbar: true,
            bind: {
                store: '{mystore}'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'commandtoolbar',
                            showRowAddBtn: true,
                            showRowDelBtn: true,
                            showRegBtn: true,
                            showReloadBtn: true,
                            showModBtn: true,
                            showSaveBtn: true,
                            showCloseBtn: false
                        }
                    ]
                }
            ],
            plugins: [
                {
                    ptype: 'cellediting'
                }
            ],
            selModel: {
                selType: 'checkboxmodel',
                mode: 'SINGLE'
            },
            listeners: {
                select: 'onEuigridSelect',
                regbtnclick: 'onEuigridRegbtnClick'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 100,
                    dataIndex: 'MSG_ID',
                    text: 'MSG_ID',
                    editor: {
                        xtype: 'textfield',
                        bind: {
                            value: '{messageRecord.MSG_ID}'
                        }
                    }
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'MSG_LABEL',
                    text: 'MSG_LABEL',
                    editor: {
                        xtype: 'textfield',
                        bind: {
                            value: '{messageRecord.MSG_LABEL}'
                        }
                    }
                }
            ]
        }
    ]

});