/*
 * File: app/model/Base.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.model.Base', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'MSG_ID',
            validators: [
                {
                    type: 'length',
                    minOnlyMessage: '최소 10자 이상입니다.',
                    min: 10
                }
            ]
        },
        {
            name: 'col1'
        },
        {
            convert: function(v, rec) {
                return rec.get('col1')+'@'+rec.get('col2');
            },
            name: 'col2'
        },
        {
            convert: function(v, rec) {
                return rec.get('col2')+'@'+rec.get('col3');
            },
            name: 'col3'
        }
    ]
});