/*
 * File: app/view/GoogleMapViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.GoogleMapViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.googlemap',

    onComponentRender: function(component, eOpts) {
        var mapOptions = {
            zoom: 15,
            center: new google.maps.LatLng(36.5,127.5)	// #2
        };
        var map = new google.maps.Map(component.el.dom,	// #3
        mapOptions);
        var weatherLayer = new google.maps.weather.WeatherLayer(); // #4
        weatherLayer.setMap(map);	// #5
        var cloudLayer = new google.maps.weather.CloudLayer();
        cloudLayer.setMap(map);
    }

});
