/*
 * File: app/view/MyContainer1.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.MyContainer1', {
    extend: 'Ext.container.Container',
    alias: 'widget.mycontainer1',

    requires: [
        'euisa.view.MyContainer1ViewModel',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Bar',
        'Ext.chart.Legend',
        'Ext.XTemplate',
        'Ext.chart.series.Line',
        'Ext.chart.interactions.PanZoom'
    ],

    viewModel: {
        type: 'mycontainer1'
    },
    height: 250,
    width: 400,

    items: [
        {
            xtype: 'cartesian',
            height: 250,
            width: 400,
            insetPadding: 20,
            axes: [
                {
                    type: 'category',
                    fields: [
                        'x'
                    ],
                    title: 'Category Axis',
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    fields: [
                        'y'
                    ],
                    position: 'left',
                    title: 'Numeric Axis'
                }
            ],
            series: [
                {
                    type: 'bar',
                    xField: 'x',
                    yField: [
                        'y'
                    ]
                },
                {
                    type: 'bar',
                    label: {
                        display: 'insideEnd',
                        field: 'y',
                        color: '#333',
                        'text-anchor': 'middle'
                    },
                    xField: 'x',
                    yField: [
                        'y'
                    ]
                }
            ],
            legend: {
                xtype: 'legend',
                dock: 'top',
                itemSelector: 'div',
                itemTpl: [
                    'Data View Item {string}'
                ]
            }
        },
        {
            xtype: 'cartesian',
            height: 250,
            width: 400,
            colors: [
                '#115fa6',
                '#94ae0a',
                '#a61120',
                '#ff8809',
                '#ffd13e',
                '#a61187',
                '#24ad9a',
                '#7c7474',
                '#a66111'
            ],
            axes: [
                {
                    type: 'category',
                    fields: [
                        'x'
                    ],
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    fields: [
                        'y1',
                        'y2'
                    ],
                    grid: {
                        odd: {
                            fill: '#e8e8e8'
                        }
                    },
                    position: 'left'
                }
            ],
            series: [
                {
                    type: 'line',
                    xField: 'x'
                },
                {
                    type: 'line',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    xField: 'x'
                }
            ],
            interactions: [
                {
                    type: 'panzoom'
                }
            ]
        }
    ]

});