/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'euisa.view.MyPanelViewModel',
        'euisa.view.main.LeftMenu2',
        'euisa.view.GoogleMap',
        'Ext.tree.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.Img',
        'eui.toolbar.Command',
        'Ext.tree.View',
        'Ext.grid.property.Grid'
    ],

    viewModel: {
        type: 'mypanel'
    },
    height: 800,
    layout: 'border',
    title: 'EcoSystem',

    items: [
        {
            xtype: 'main.leftmenu2',
            collapsed: false,
            collapsible: true,
            region: 'west',
            split: true
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            items: [
                {
                    xtype: 'panel',
                    height: 600,
                    liquidLayout: true,
                    width: 200,
                    layout: 'fit',
                    title: '작업자위치정보',
                    items: [
                        {
                            xtype: 'container',
                            height: 500,
                            layout: 'absolute',
                            items: [
                                {
                                    xtype: 'gmap',
                                    height: 1024,
                                    width: 1024
                                },
                                {
                                    xtype: 'image',
                                    x: 360,
                                    y: 290,
                                    constrain: true,
                                    shim: false,
                                    cls: 'gmap',
                                    draggable: true,
                                    liveDrag: true,
                                    style: 'z-index : 100',
                                    width: 100,
                                    src: 'resources/imgs/chart2.PNG'
                                },
                                {
                                    xtype: 'image',
                                    x: 180,
                                    y: 460,
                                    constrain: true,
                                    shim: false,
                                    cls: 'gmap',
                                    draggable: true,
                                    liveDrag: true,
                                    style: 'z-index : 100',
                                    width: 100,
                                    src: 'resources/imgs/chart1.PNG'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'commandtoolbar',
                            dock: 'top',
                            showRowAddBtn: true,
                            showRowDelBtn: true,
                            showRegBtn: true,
                            showReloadBtn: true,
                            showModBtn: true,
                            showSaveBtn: true,
                            showCloseBtn: true
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'east',
            width: 250,
            collapsed: false,
            collapsible: true,
            title: 'Map History',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'treepanel',
                            title: 'My History',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        text: '전력구내 작업자위치정보',
                                        expanded: false,
                                        children: [
                                            {
                                                text: '작업자1',
                                                leaf: true,
                                                pgmClass: 'euisa.view.grid.Basic',
                                                pgmAlias: 'samplebasicgrid'
                                            },
                                            {
                                                text: '송전탑A01',
                                                leaf: true,
                                                pgmClass: 'euisa.view.grid.MergeGrid',
                                                pgmAlias: 'samplemergegrid'
                                            }
                                        ]
                                    },
                                    {
                                        text: '전력컨설팅 서비스',
                                        expanded: false,
                                        children: [
                                            {
                                                text: '작업요원',
                                                leaf: true,
                                                pgmClass: 'euisa.view.form.Panel',
                                                pgmAlias: 'sampleform'
                                            },
                                            {
                                                text: '현장관리자',
                                                leaf: true,
                                                pgmClass: 'euisa.view.form.Panel',
                                                pgmAlias: 'sampleform'
                                            }
                                        ]
                                    }
                                ]
                            },
                            rootVisible: false,
                            tabConfig: {
                                xtype: 'tab',
                                dock: 'left',
                                width: 100
                            }
                        },
                        {
                            xtype: 'treepanel',
                            title: 'Team History',
                            root: {
                                expanded: true,
                                children: [
                                    {
                                        text: '전력구내 작업자위치정보',
                                        expanded: false,
                                        children: [
                                            {
                                                text: '작업자1',
                                                leaf: true,
                                                pgmClass: 'euisa.view.grid.Basic',
                                                pgmAlias: 'samplebasicgrid'
                                            },
                                            {
                                                text: '송전탑A01',
                                                leaf: true,
                                                pgmClass: 'euisa.view.grid.MergeGrid',
                                                pgmAlias: 'samplemergegrid'
                                            }
                                        ]
                                    },
                                    {
                                        text: '전력컨설팅 서비스',
                                        expanded: false,
                                        children: [
                                            {
                                                text: '작업요원',
                                                leaf: true,
                                                pgmClass: 'euisa.view.form.Panel',
                                                pgmAlias: 'sampleform'
                                            },
                                            {
                                                text: '현장관리자',
                                                leaf: true,
                                                pgmClass: 'euisa.view.form.Panel',
                                                pgmAlias: 'sampleform'
                                            }
                                        ]
                                    }
                                ]
                            },
                            rootVisible: false,
                            tabConfig: {
                                xtype: 'tab',
                                dock: 'left',
                                width: 100
                            }
                        }
                    ]
                },
                {
                    xtype: 'propertygrid',
                    flex: 1,
                    height: 200,
                    title: '전력선 > 전신주',
                    source: {
                        크기: 'String',
                        애자수: true,
                        최초설치일: '2016-06-01T10:56:12',
                        담당자: '홍길동'
                    }
                }
            ]
        }
    ]

});