/*
 * File: app/view/main/LeftMenu.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.main.LeftMenu', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.leftmenu',

    requires: [
        'euisa.view.main.LeftMenuViewModel',
        'Ext.tree.View'
    ],

    viewModel: {
        type: 'mainleftmenu'
    },
    defaultListenerScope: true,
    width: 150,
    title: 'My Tree Panel',
    root: {
        expanded: true,
        children: [
            {
                text: 'Grid',
                expanded: true,
                children: [
                    {
                        text: 'Basic Grid',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.Basic',
                        pgmAlias: 'samplebasicgrid'
                    }
                ]
            },
            {
                text: 'Form',
                expanded: true,
                children: [
                    {
                        text: 'FormPanel',
                        leaf: true,
                        pgmClass: 'euisa.view.form.Panel',
                        pgmAlias: 'sampleform'
                    }
                ]
            }
        ]
    },
    rootVisible: false,

    listeners: {
        itemclick: 'onTreepanelItemClick'
    },

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        if (record.get('leaf') === true) {
            var mainTabObj = Ext.ComponentQuery.query('#maintab');


            // var centerpanel = this.AccountMain().down('maintab');
            var pgm = {
                pgmClass: 'Ext.panel.Panel',
                pgmAlias: 'panel'
            };
            if (record.get('pgmClass')) {
                pgm = {
                    pgmClass: record.get('pgmClass'),
                    pgmAlias: record.get('pgmAlias')
                };
            }

            var tab = mainTabObj[0].down('[itemId=' + pgm.pgmClass + ']');
            if(!tab){
                Ext.require(pgm.pgmClass, function () {
                    var className = Ext.ClassManager.getNameByAlias('widget.' + pgm.pgmAlias);
                    var ViewClass = Ext.ClassManager.get(pgm.pgmClass);
                    tab = new ViewClass();
                    if (Ext.isEmpty(record.get('pgmClass'))) {
                        tab.add({
                            xtype: 'TemplateA'
                        });
                    }

                    tab.title = record.get('text');
                    tab.itemId = pgm.pgmClass;
                    tab.closable = true;
                    mainTabObj[0].add(tab);
                });
            }
            mainTabObj[0].setActiveItem(tab);

        }
    }

});