/*
 * File: app/view/main/LeftMenu2.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.main.LeftMenu2', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.main.leftmenu2',

    requires: [
        'euisa.view.main.LeftMenuViewModel1',
        'Ext.tree.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'main.leftmenu2'
    },
    defaultListenerScope: true,
    width: 150,
    title: 'ToolBox',
    root: {
        expanded: false,
        children: [
            {
                text: 'Map',
                expanded: false,
                children: [
                    {
                        text: '시도별전국지도',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.Basic',
                        pgmAlias: 'samplebasicgrid'
                    },
                    {
                        text: '전력선로',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.MergeGrid',
                        pgmAlias: 'samplemergegrid'
                    },
                    {
                        text: '경기도',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.MergeGrid',
                        pgmAlias: 'samplemergegrid'
                    },
                    {
                        text: '서울시',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.MergeGrid',
                        pgmAlias: 'samplemergegrid'
                    }
                ]
            },
            {
                text: '전력시설',
                expanded: false,
                children: [
                    {
                        text: '발전소',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.Basic',
                        pgmAlias: 'samplebasicgrid'
                    },
                    {
                        text: '송전탑',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.MergeGrid',
                        pgmAlias: 'samplemergegrid'
                    },
                    {
                        text: '전신주',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.MergeGrid',
                        pgmAlias: 'samplemergegrid'
                    },
                    {
                        text: '송전탑',
                        leaf: true,
                        pgmClass: 'euisa.view.grid.MergeGrid',
                        pgmAlias: 'samplemergegrid'
                    }
                ]
            },
            {
                text: '사람',
                expanded: false,
                children: [
                    {
                        text: '작업요원',
                        leaf: true,
                        pgmClass: 'euisa.view.form.Panel',
                        pgmAlias: 'sampleform'
                    },
                    {
                        text: '현장관리자',
                        leaf: true,
                        pgmClass: 'euisa.view.form.Panel',
                        pgmAlias: 'sampleform'
                    }
                ]
            }
        ]
    },
    rootVisible: false,

    listeners: {
        itemclick: 'onTreepanelItemClick'
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Label',
                    hideLabel: true
                }
            ]
        }
    ],

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        if (record.get('leaf') === true) {
            var mainTabObj = Ext.ComponentQuery.query('#maintab');


            // var centerpanel = this.AccountMain().down('maintab');
            var pgm = {
                pgmClass: 'Ext.panel.Panel',
                pgmAlias: 'panel'
            };
            if (record.get('pgmClass')) {
                pgm = {
                    pgmClass: record.get('pgmClass'),
                    pgmAlias: record.get('pgmAlias')
                };
            }

            var tab = mainTabObj[0].down('[itemId=' + pgm.pgmClass + ']');
            if(!tab){
                Ext.require(pgm.pgmClass, function () {
                    var className = Ext.ClassManager.getNameByAlias('widget.' + pgm.pgmAlias);
                    var ViewClass = Ext.ClassManager.get(pgm.pgmClass);
                    tab = new ViewClass();
                    if (Ext.isEmpty(record.get('pgmClass'))) {
                        tab.add({
                            xtype: 'TemplateA'
                        });
                    }

                    tab.title = record.get('text');
                    tab.itemId = pgm.pgmClass;
                    tab.closable = true;
                    mainTabObj[0].add(tab);
                });
            }
            mainTabObj[0].setActiveItem(tab);

        }
    }

});