/*
 * File: app/view/main/Main.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.main.Main', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainmain',

    requires: [
        'euisa.view.main.MainViewModel',
        'euisa.view.form.Panel',
        'euisa.view.main.LeftMenu',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.tree.Panel'
    ],

    viewModel: {
        type: 'main'
    },
    layout: 'border',

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            itemId: 'maintab',
            margin: '5 5 0 0',
            items: [
                {
                    xtype: 'sampleform'
                }
            ]
        },
        {
            xtype: 'leftmenu',
            margin: '5 0 0 5',
            width: 200,
            collapsible: true,
            title: 'Menu#{행추가아이콘}',
            region: 'west',
            split: true
        }
    ]

});