/*
 * File: app/view/form/CompanyCombo.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.form.CompanyCombo', {
    extend: 'eui.form.field.ComboBox',
    alias: 'widget.companycombo',

    requires: [
        'euisa.view.form.CompanyComboViewModel'
    ],

    viewModel: {
        type: 'formcompanycombo'
    },
    fieldLabel: 'Label',
    editable: false,
    emptyText: '선택하세요',
    autoLoadOnValue: true,
    displayField: 'name',
    valueField: 'code',

    bind: {
        store: '{cmpstore}'
    }

});