/*
 * File: app/view/form/Panel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.form.Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sampleform',

    requires: [
        'euisa.view.form.PanelViewModel',
        'eui.form.Panel',
        'eui.form.RadioGroup',
        'Ext.form.field.Radio',
        'eui.form.field.Text'
    ],

    viewModel: {
        type: 'sampleform'
    },
    defaults: {
        margin: 5
    },
    title: 'EUI 사용하기',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'euiform',
            flex: 1,
            frame: true,
            defaults: {
                allowBlank: false
            },
            title: 'EUI 폼',
            tableColumns: 2,
            items: [
                {
                    xtype: 'euiradiogroup',
                    fieldLabel: '회원구분',
                    bind: {
                        value: '{regMember.memberFlag}'
                    },
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: '일반',
                            checked: true,
                            inputValue: 'N'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: '관리자'
                        }
                    ]
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '아이디'
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '비밀번호'
                }
            ]
        }
    ]

});