/*
 * File: app/view/form/Panel.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('euisa.view.form.Panel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sampleform',

    requires: [
        'euisa.view.form.PanelViewModel',
        'euisa.view.form.CompanyCombo',
        'eui.form.Panel',
        'eui.form.RadioGroup',
        'Ext.form.field.Radio',
        'eui.form.field.Text',
        'eui.form.CheckboxGroup',
        'eui.form.field.Date',
        'eui.form.field.ComboBox',
        'eui.form.field.File',
        'eui.form.field.Number'
    ],

    viewModel: {
        type: 'sampleform'
    },
    defaults: {
        margin: 5
    },
    title: 'EUI 사용하기',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'euiform',
            flex: 1,
            frame: true,
            defaults: {
                allowBlank: false
            },
            layout: 'table',
            title: 'EUI 폼',
            tableColumns: 2,
            items: [
                {
                    xtype: 'euiradiogroup',
                    fieldLabel: '회원구분',
                    bind: {
                        value: '{regMember.memberFlag}'
                    },
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: '일반',
                            inputValue: 'N'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: '관리자',
                            inputValue: 'S'
                        }
                    ]
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '아이디'
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '비밀번호',
                    inputType: 'password'
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '비밀번호확인',
                    inputType: 'password'
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '성명'
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '이메일',
                    inputType: 'email'
                },
                {
                    xtype: 'euitext',
                    fieldLabel: '연락처'
                },
                {
                    xtype: 'euiradiogroup',
                    fieldLabel: '성별',
                    bind: {
                        value: '{regMember.gender}'
                    },
                    items: [
                        {
                            xtype: 'radiofield',
                            boxLabel: '남성',
                            inputValue: 'M'
                        },
                        {
                            xtype: 'radiofield',
                            boxLabel: '여성',
                            inputValue: 'F'
                        }
                    ]
                },
                {
                    xtype: 'euicheckboxgroup',
                    colspan: 2,
                    defaults: {
                        name: 'job'
                    },
                    fieldLabel: '직업',
                    columns: 6,
                    vertical: true,
                    bind: {
                        value: '{regMember.job}'
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            boxLabel: '회사원',
                            inputValue: 'A1'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: '연구원',
                            inputValue: 'A2'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: '연구원',
                            inputValue: 'A2'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: '연구원',
                            inputValue: 'A2'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: '연구원',
                            inputValue: 'A2'
                        },
                        {
                            xtype: 'checkboxfield',
                            boxLabel: '연구원',
                            inputValue: 'A2'
                        }
                    ]
                },
                {
                    xtype: 'euidate',
                    fieldLabel: '생년월일'
                },
                {
                    xtype: 'companycombo',
                    fieldLabel: '회사'
                },
                {
                    xtype: 'euifile',
                    fieldLabel: '파일'
                },
                {
                    xtype: 'euinumber',
                    fieldLabel: '연봉'
                }
            ]
        }
    ]

});